### ISSUE TITLE
Example EntrypointParameters usage

### ISSUE THREAD

**Issue by cheemingli** [michaellwest/docker-https#5]
Do you have an example of the `EntrypointParameters` usage? 
I can't figure out the correct way to pass in the `WatchDirectoryParameters` of the `Development.ps1` script.

**Comment by michaellwest** [comment]
@bic742 Do you happen to have an example to share with @cheemingli ?

**Comment by bic742** [comment]
My entrypoint looks like this:

```
  cm:
    image: ${REGISTRY}sitecore-xp-spe-standalone:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -NoLogo -NoProfile -File C:\\startup\\startup.ps1
    ports:
      - "44001:80"
      - "44002:443"
    volumes:
      - ${LICENSE_PATH}:C:\license:ro
      - .\startup:C:\startup
      - .\data\cm:C:\inetpub\wwwroot\App_Data\logs
      - .\src\sitecore:C:\src
      - ${UNICORN_PATH}:${UNICORN_PATH}
```
